all:
  children:
    laptop:
      hosts:
        g14:
          ansible_host: 127.0.0.1
    server:
      hosts:
        fedora-server:
          ansible_host: 192.168.1.9
    pi:
      hosts:
        pi400:
          ansible_host: 192.168.1.7
        pi5:
          ansible_host: 192.168.1.11
    mac:
      hosts:
        macmini:
          ansible_host: 192.168.1.10
